# Generated by Django 4.1.2 on 2022-10-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengemudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('pool', models.CharField(max_length=50)),
                ('bus', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pemeriksaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('tensi', models.CharField(max_length=10)),
                ('suhu', models.FloatField()),
                ('jam_tidur', models.FloatField()),
                ('kondisi', models.CharField(max_length=200)),
                ('pengemudi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LayakMengemudi.pengemudi')),
            ],
        ),
    ]
