# Generated by Django 4.1.2 on 2022-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0002_pengemudi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengemudi',
            name='periksa_terakhir',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pengemudi',
            name='qrcode_path',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
