# Generated by Django 4.1.3 on 2022-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0003_pengemudi_periksa_terakhir_pengemudi_qrcode_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengemudi',
            name='nik',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
