# Generated by Django 4.1.3 on 2022-11-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0004_pengemudi_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengemudi',
            name='pasfoto_path',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
