# Generated by Django 4.1.3 on 2022-11-13 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0005_pengemudi_pasfoto_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengemudi',
            name='alamat',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='pengemudi',
            name='kota_kelahiran',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='pengemudi',
            name='tanggal_lahir',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
