# Generated by Django 4.1.3 on 2022-11-20 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0006_pengemudi_alamat_pengemudi_kota_kelahiran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='status',
            field=models.CharField(choices=[('L', 'Layak Jalan'), ('TL', 'Tidak Layak Jalan')], default='TL', max_length=2),
        ),
        migrations.AlterField(
            model_name='pengemudi',
            name='tanggal_lahir',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
    ]
