# Generated by Django 4.1.3 on 2022-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0007_pemeriksaan_status_alter_pengemudi_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengemudi',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
