# Generated by Django 4.1.3 on 2022-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0008_alter_pengemudi_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengemudi',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pengemudi',
            name='kota_kelahiran',
            field=models.CharField(max_length=50),
        ),
    ]
