# Generated by Django 4.1.3 on 2022-11-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0011_pengemudi_pasfoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengemudi',
            name='pasfoto_path',
        ),
    ]
