# Generated by Django 4.1.3 on 2023-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0013_alter_pengemudi_pasfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengemudi',
            name='pasfoto',
            field=models.ImageField(height_field='200', upload_to='images/', width_field='150'),
        ),
    ]
