# Generated by Django 4.1.7 on 2023-02-19 13:06

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0015_alter_pengemudi_pasfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='alkohol',
            field=models.CharField(choices=[('A', 'Terdeteksi Alkohol'), ('NA', 'Tidak Terdeteksi Alkohol')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='gula_darah',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='kolesterol',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengemudi',
            name='pasfoto',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 400], upload_to='images/%Y%m'),
        ),
    ]
