# Generated by Django 4.1.7 on 2023-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0019_alter_pengemudi_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengemudi',
            name='bus',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pengemudi',
            name='pool',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
