# Generated by Django 4.1.7 on 2023-03-25 05:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0021_alter_pengemudi_pasfoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengemudi',
            name='pasfoto',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 400], upload_to='images/%Y%m'),
        ),
    ]
