# Generated by Django 4.1.7 on 2023-03-25 07:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0023_alter_pengemudi_pasfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemeriksaan',
            name='napza',
            field=models.CharField(choices=[('+', 'Terdekteksi NAPZA'), ('-', 'Tidak terdeteksi NAPZA')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='gula_darah',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaan',
            name='kolesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pengemudi',
            name='pasfoto',
            field=django_resized.forms.ResizedImageField(crop=None, default='no_pic.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 400], upload_to='images/%Y%m'),
        ),
    ]
