# Generated by Django 4.1.7 on 2023-03-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0024_pemeriksaan_napza_alter_pemeriksaan_gula_darah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaan',
            name='tensi',
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='diastolik',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemeriksaan',
            name='sistolik',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
