# Generated by Django 4.1.7 on 2023-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayakMengemudi', '0025_remove_pemeriksaan_tensi_pemeriksaan_diastolik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemeriksaan',
            name='alkohol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
